spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: KusheduSound
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  storage:
    tracks-path: ./storage/tracks
  test-user: system_admin